wallet:
  title: "&cWallet"
  size: 9

wallet-item:
  material: STICK
  custommodeldata: 9


whitelisted-items:
  1:
    material: STICK
    custommodeldata: 1
  2:
    material: STICK
    custommodeldata: 2
  3:
    material: PAPER
    custommodeldata: 0



Lang:
  item-not-whitelisted: "&cSorry, you can't store this item in your wallet."
  wallet-give: "&cYou gave a wallet correctly."
  wallet-received: "&cYou received a wallet."
  playeroffline: "&cThis player is not online."
  nopermission: "&cYou don't have permission to run this command."
  command-syntax: "&cPlease use /wallet give <player>"